name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_GITHUB_PAT }}
          persist-credentials: true
          fetch-depth: 0

      - name: environment
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18

      - name: install dependencies
        run: npm i

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
